/* GENERATED by kynth-ops/tools/social-rail.mjs — do not edit by hand.
 *
 * Regenerate:  node kynth-ops/tools/social-rail.mjs --slug tearline \
 *                --out <this file> --ground dark --align left --container 1072
 *
 * The link set is derived from kynth-ops/social/accounts.json, the account registry — never
 * typed here. Editing this file by hand puts one product's idea of which accounts exist back in
 * one product's repo, which is the state this replaced: measured 2026-08-21, thirty-six of the
 * estate's forty-two live product sites linked no social account at all and the six that did
 * disagreed with each other and with the registry.
 *
 * ⛔ ICON-ONLY, AND IT IS ITS OWN ROW — NEVER A FOOTER COLUMN. The landing standard's §7b fails a
 * footer whose columns run more than two rows apart and finds a column by layout, so a labelled
 * block of ten links is a §7b failure on every product at once. §7 already exempts an icon-only
 * social link ("already a mark"). The destination is carried by aria-label and title.
 *
 * ⛔ THE COLOUR IS THE PLATFORM'S, NOT THIS PRODUCT'S ACCENT, AND THAT IS THE ONE PLACE IN THE
 * ESTATE WHERE THAT IS TRUE. Isaiah, 2026-08-21: "just use the platforms' color please. blue for
 * bsky, et". These marks belong to somebody else, so the rail reads as a set of destinations
 * rather than as more of this product's own furniture.
 *
 * ⛔ AND THE GROUND IS MEASURED, NEVER ASSUMED — this file was generated for a dark
 * footer. Five of the ten platforms brand in near-black (X, Threads, Dev.to, TikTok, GitHub), so
 * one hex each would put five invisible glyphs in the middle of the rail on every dark footer,
 * which is the failure nothing errors on. Each link carries the platform's own light-ground and
 * dark-ground values and the rule below picks by the ground this footer actually paints.
 *
 * Solar bold-duotone icons, CC BY 4.0 by 480 Design — https://github.com/480-Design/Solar-Icon-Set
 */
import { Fragment } from "react";
import type { CSSProperties } from "react";

type Link = { href: string; mark: string; label: string; onLight: string; onDark: string };

const BODIES: Record<string, string> = {
  "x": "<path fill=\"currentColor\" d=\"M14.234 10.162L22.977 0h-2.072l-7.591 8.824L7.251 0H.258l9.168 13.343L.258 24H2.33l8.016-9.318L16.749 24h6.993zm-2.837 3.299l-.929-1.329L3.076 1.56h3.182l5.965 8.532l.929 1.329l7.754 11.09h-3.182z\"/>",
  "threads": "<path fill=\"currentColor\" d=\"M18.263 11.097c-.03-3.486-1.92-5.586-5.111-5.586c-2.13 0-3.922.963-4.863 2.499l2.062 1.438c.535-.843 1.272-1.543 2.628-1.543c1.528 0 2.318.85 2.544 2.431a15 15 0 0 0-2.236-.173c-4.125 0-6.068 1.867-6.068 4.336s1.943 3.99 4.804 3.99c3.139 0 5.013-2.115 5.781-4.735c.798.361 1.348 1.204 1.348 2.47c0 3.387-3.907 5.232-7.22 5.232c-4.885 0-8.077-3.207-8.077-8.424c0-6.392 4.223-10.487 9.9-10.487c3.808 0 5.69 1.671 6.97 3.914l2.108-1.475C21.44 2.078 18.331 0 13.663 0C6.227 0 1.168 5.277 1.168 12.934c0 7 4.953 11.066 10.856 11.066c4.878 0 9.809-2.846 9.809-7.716c0-2.545-1.46-4.231-3.569-5.187m-6.33 4.855c-1.077 0-2.026-.512-2.026-1.453c0-1.483 1.822-1.934 3.606-1.934c.678 0 1.34.045 1.927.173c-.422 1.927-1.671 3.215-3.508 3.214Z\"/>",
  "instagram": "<path fill=\"currentColor\" d=\"M7.03.084c-1.277.06-2.149.264-2.91.563a5.9 5.9 0 0 0-2.124 1.388a5.9 5.9 0 0 0-1.38 2.127C.321 4.926.12 5.8.064 7.076s-.069 1.688-.063 4.947s.021 3.667.083 4.947c.061 1.277.264 2.149.563 2.911c.308.789.72 1.457 1.388 2.123a5.9 5.9 0 0 0 2.129 1.38c.763.295 1.636.496 2.913.552c1.278.056 1.689.069 4.947.063s3.668-.021 4.947-.082c1.28-.06 2.147-.265 2.91-.563a5.9 5.9 0 0 0 2.123-1.388a5.9 5.9 0 0 0 1.38-2.129c.295-.763.496-1.636.551-2.912c.056-1.28.07-1.69.063-4.948c-.006-3.258-.02-3.667-.081-4.947c-.06-1.28-.264-2.148-.564-2.911a5.9 5.9 0 0 0-1.387-2.123a5.9 5.9 0 0 0-2.128-1.38c-.764-.294-1.636-.496-2.914-.55C15.647.009 15.236-.006 11.977 0S8.31.021 7.03.084m.14 21.693c-1.17-.05-1.805-.245-2.228-.408a3.7 3.7 0 0 1-1.382-.895a3.7 3.7 0 0 1-.9-1.378c-.165-.423-.363-1.058-.417-2.228c-.06-1.264-.072-1.644-.08-4.848c-.006-3.204.006-3.583.061-4.848c.05-1.169.246-1.805.408-2.228c.216-.561.477-.96.895-1.382a3.7 3.7 0 0 1 1.379-.9c.423-.165 1.057-.361 2.227-.417c1.265-.06 1.644-.072 4.848-.08c3.203-.006 3.583.006 4.85.062c1.168.05 1.804.244 2.227.408c.56.216.96.475 1.382.895s.681.817.9 1.378c.165.422.362 1.056.417 2.227c.06 1.265.074 1.645.08 4.848c.005 3.203-.006 3.583-.061 4.848c-.051 1.17-.245 1.805-.408 2.23c-.216.56-.477.96-.896 1.38a3.7 3.7 0 0 1-1.378.9c-.422.165-1.058.362-2.226.418c-1.266.06-1.645.072-4.85.079s-3.582-.006-4.848-.06m9.783-16.192a1.44 1.44 0 1 0 1.437-1.442a1.44 1.44 0 0 0-1.437 1.442M5.839 12.012a6.161 6.161 0 1 0 12.323-.024a6.162 6.162 0 0 0-12.323.024M8 12.008A4 4 0 1 1 12.008 16A4 4 0 0 1 8 12.008\"/>",
  "linkedin": "<path fill=\"currentColor\" d=\"M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037c-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85c3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.06 2.06 0 0 1-2.063-2.065a2.064 2.064 0 1 1 2.063 2.065m1.782 13.019H3.555V9h3.564zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0z\"/>",
  "bluesky": "<path fill=\"currentColor\" d=\"M5.202 2.857C7.954 4.922 10.913 9.11 12 11.358c1.087-2.247 4.046-6.436 6.798-8.501C20.783 1.366 24 .213 24 3.883c0 .732-.42 6.156-.667 7.037c-.856 3.061-3.978 3.842-6.755 3.37c4.854.826 6.089 3.562 3.422 6.299c-5.065 5.196-7.28-1.304-7.847-2.97c-.104-.305-.152-.448-.153-.327c0-.121-.05.022-.153.327c-.568 1.666-2.782 8.166-7.847 2.97c-2.667-2.737-1.432-5.473 3.422-6.3c-2.777.473-5.899-.308-6.755-3.369C.42 10.04 0 4.615 0 3.883c0-3.67 3.217-2.517 5.202-1.026\"/>",
  "devdotto": "<path fill=\"currentColor\" d=\"M7.42 10.05c-.18-.16-.46-.23-.84-.23H6l.02 2.44l.04 2.45l.56-.02c.41 0 .63-.07.83-.26c.24-.24.26-.36.26-2.2c0-1.91-.02-1.96-.29-2.18M0 4.94v14.12h24V4.94zM8.56 15.3c-.44.58-1.06.77-2.53.77H4.71V8.53h1.4c1.67 0 2.16.18 2.6.9c.27.43.29.6.32 2.57c.05 2.23-.02 2.73-.47 3.3m5.09-5.47h-2.47v1.77h1.52v1.28l-.72.04l-.75.03v1.77l1.22.03l1.2.04v1.28h-1.6c-1.53 0-1.6-.01-1.87-.3l-.3-.28v-3.16c0-3.02.01-3.18.25-3.48c.23-.31.25-.31 1.88-.31h1.64v1.3zm4.68 5.45c-.17.43-.64.79-1 .79c-.18 0-.45-.15-.67-.39c-.32-.32-.45-.63-.82-2.08l-.9-3.39l-.45-1.67h.76c.4 0 .75.02.75.05c0 .06 1.16 4.54 1.26 4.83c.04.15.32-.7.73-2.3l.66-2.52l.74-.04c.4-.02.73 0 .73.04c0 .14-1.67 6.38-1.8 6.68z\"/>",
  "hashnode": "<path fill=\"currentColor\" d=\"m22.351 8.019l-6.37-6.37a5.63 5.63 0 0 0-7.962 0l-6.37 6.37a5.63 5.63 0 0 0 0 7.962l6.37 6.37a5.63 5.63 0 0 0 7.962 0l6.37-6.37a5.63 5.63 0 0 0 0-7.962M12 15.953a3.953 3.953 0 1 1 0-7.906a3.953 3.953 0 0 1 0 7.906\"/>",
  "youtube": "<path fill=\"currentColor\" d=\"M23.498 6.186a3.02 3.02 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.02 3.02 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.02 3.02 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.02 3.02 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814M9.545 15.568V8.432L15.818 12z\"/>"
};

const GROUPS: { label: string; links: Link[] }[] = [
  {
    "label": "Kynth Studios",
    "links": [
      {
        "href": "https://x.com/kynthstudios",
        "mark": "x",
        "onLight": "#000000", // third-party-mark: X brand colour, never this product's accent
        "onDark": "#FFFFFF", // third-party-mark: X brand colour, never this product's accent
        "label": "Kynth Studios on X — @kynthstudios"
      },
      {
        "href": "https://www.threads.com/@kynthstudios",
        "mark": "threads",
        "onLight": "#000000", // third-party-mark: Threads brand colour, never this product's accent
        "onDark": "#FFFFFF", // third-party-mark: Threads brand colour, never this product's accent
        "label": "Kynth Studios on Threads — @kynthstudios"
      },
      {
        "href": "https://www.instagram.com/kynthstudios/",
        "mark": "instagram",
        "onLight": "#E4405F", // third-party-mark: Instagram brand colour, never this product's accent
        "onDark": "#E4405F", // third-party-mark: Instagram brand colour, never this product's accent
        "label": "Kynth Studios on Instagram — @kynthstudios"
      },
      {
        "href": "https://www.linkedin.com/company/kynth-studios",
        "mark": "linkedin",
        "onLight": "#0A66C2", // third-party-mark: LinkedIn brand colour, never this product's accent
        "onDark": "#70B5F9", // third-party-mark: LinkedIn brand colour, never this product's accent
        "label": "Kynth Studios on LinkedIn"
      },
      {
        "href": "https://bsky.app/profile/kynth.studio",
        "mark": "bluesky",
        "onLight": "#0285FF", // third-party-mark: Bluesky brand colour, never this product's accent
        "onDark": "#4CA9FF", // third-party-mark: Bluesky brand colour, never this product's accent
        "label": "Kynth Studios on Bluesky — kynth.studio"
      },
      {
        "href": "https://dev.to/kynth",
        "mark": "devdotto",
        "onLight": "#0A0A0A", // third-party-mark: Dev.to brand colour, never this product's accent
        "onDark": "#FFFFFF", // third-party-mark: Dev.to brand colour, never this product's accent
        "label": "Kynth Studios on Dev.to — @kynth"
      },
      {
        "href": "https://kynth.hashnode.dev/",
        "mark": "hashnode",
        "onLight": "#2962FF", // third-party-mark: Hashnode brand colour, never this product's accent
        "onDark": "#6E93FF", // third-party-mark: Hashnode brand colour, never this product's accent
        "label": "Kynth Studios on Hashnode — kynth.hashnode.dev"
      },
      {
        "href": "https://www.youtube.com/@KynthStudios",
        "mark": "youtube",
        "onLight": "#FF0000", // third-party-mark: YouTube brand colour, never this product's accent
        "onDark": "#FF0000", // third-party-mark: YouTube brand colour, never this product's accent
        "label": "Kynth Studios on YouTube — @KynthStudios"
      }
    ]
  },
  {
    "label": "@kyisaiah47",
    "links": [
      {
        "href": "https://x.com/kyisaiah47",
        "mark": "x",
        "onLight": "#000000", // third-party-mark: X brand colour, never this product's accent
        "onDark": "#FFFFFF", // third-party-mark: X brand colour, never this product's accent
        "label": "@kyisaiah47 on X"
      },
      {
        "href": "https://www.linkedin.com/in/kyisaiah47",
        "mark": "linkedin",
        "onLight": "#0A66C2", // third-party-mark: LinkedIn brand colour, never this product's accent
        "onDark": "#70B5F9", // third-party-mark: LinkedIn brand colour, never this product's accent
        "label": "@kyisaiah47 on LinkedIn"
      }
    ]
  }
];

export default function SocialRail() {
  return (
    <div className={"kynth-social"}>
      {/* Hover, focus and the rail layout cannot be written inline, and a rule in this repo's
          stylesheet would be a forty-fifth place to keep in sync. Every selector is scoped under
          .kynth-social, so it cannot reach anything else on the page. */}
      <style>{`
        /* ⛔ NO GROUP LABELS. The first build carried a quiet "KYNTH STUDIOS" / "@KYISAIAH47"
           caption over each group, to tell the studio's X apart from the founder's. Isaiah
           rejected them outright, 2026-08-21, off a rendered sheet: the labels turned a set of
           marks into a titled block bolted onto the end of the footer, which is the thing this
           replaced. The two groups are separated by a hairline instead, and every link still
           names its account in aria-label and title. */
        .kynth-social{display:flex;flex-wrap:wrap;align-items:center;gap:0;margin:0 -12px;padding:0;
          justify-content:flex-start;
          width:min(100% - 48px, 1072px);margin:0 auto;padding:0}
        /* ⛔ 44px IS A FLOOR AND THIS SHIPPED UNDER IT TWICE. 36x36 with a 2px gap is a
           precise-pointer size; it fails WCAG 2.5.8 and the adjacent-target spacing rule the
           moment the footer is read on a phone. Measured at 390px on leadgrade by the landing
           craft check and again on starreply: ten undersized controls each time, every one a rail
           link (ux-guidelines #22, #23; house standard §5 is 44).

           ⛔ AND IT IS THE BASE RULE, NOT A PHONE MEDIA QUERY. A pointer-coarse target on a
           laptop trackpad is the same target, the gate measures the desktop pass too, and one
           rule cannot disagree with itself at a breakpoint. The GLYPH is 18px and the BOX is 44
           with no gap between boxes, so the rail reads at the weight Isaiah picked while the
           touch area stays legal. The negative margin cancels the first box's inset so the
           leading mark is optically flush with the text edge above it. */
        .kynth-social a{display:inline-flex;align-items:center;justify-content:center;
          width:44px;height:44px;border-radius:999px;opacity:.92;
          transition:opacity .18s ease,background-color .18s ease;text-decoration:none}
        .kynth-social a:hover{opacity:1;background-color:color-mix(in srgb, currentColor 15%, transparent)}
        .kynth-social a:focus-visible{opacity:1;outline:2px solid currentColor;outline-offset:2px}
        .kynth-social svg{display:block;width:18px;height:18px}
        /* The group divider. flex:0 0 auto so it never absorbs slack, and it is aria-hidden
           below because it carries no meaning a reader needs — it separates the studio's accounts
           from the founder's, and both are already named on every link. */
        .kynth-social .kynth-social-sep{display:inline-block;flex:0 0 auto;width:1px;height:15px;
          margin:0 11px;background:currentColor;opacity:.22}
        .kynth-social a{color:var(--kr-on-dark)}
      `}</style>
      {GROUPS.map((g, gi) => (
        <Fragment key={g.label}>
          {gi > 0 ? <i className={"kynth-social-sep"} aria-hidden={true} /> : null}
          {g.links.map((l) => (
            <a
              key={l.href}
              href={l.href}
              target={"_blank"}
              rel={"noopener me"}
              aria-label={l.label}
              title={l.label}
              style={{ "--kr-on-light": l.onLight, "--kr-on-dark": l.onDark } as CSSProperties}
            >
              <svg
                viewBox={"0 0 24 24"}
                fill={"currentColor"}
                role={"img"}
                aria-hidden={true}
                focusable={false}
                dangerouslySetInnerHTML={{ __html: BODIES[l.mark] }}
              />
            </a>
          ))}
        </Fragment>
      ))}
    </div>
  );
}
