/* THE FOLLOW COLUMN — the ten estate destinations, as a footer column in Tearline's own row
 * grammar.
 *
 * ⛔ IT REPLACES `SocialRail.tsx`, THE ICON-ONLY STRIP UNDER THE BRAND BLOCK. Measured on
 * tearline.kynth.studio 2026-08-21 at 1440: thirty social anchors in the document for ten
 * destinations, because this footer ships in three breakpoint variants and each carried its own
 * copy of the rail. Ten of them painted at any one width, in ten third-party brand hexes — the
 * only icon family and the only set of colours on the page that were not Tearline's amber, in the
 * one slot in the footer that is not a column, a row or a bar. Isaiah, 2026-08-21: "social icons
 * need to become solar icons and better integrated not just bolted on".
 *
 * ⛔ TEARLINE HAS NO ACCOUNTS OF ITS OWN, so there is no second column beside this one — unlike
 * the wires, whose own handles keep their own column. Its own discovery surfaces are GitHub and
 * npm and those are rows in CODE, where they already were.
 *
 * ⛔ SOLAR SHIPS NO BRAND LOGOS — 0 of 7,404 ids match any platform name — so a glyph cannot draw
 * X's mark and instead MEANS what the account publishes: short posts, conversation, photographs,
 * professional writing, the open network, code posts, long-form writing, video. The label beside
 * it is what identifies the destination, which is why every row is labelled where the icon-only
 * rail was not.
 *
 * ⛔ AND ONE COLLISION WAS RESOLVED ON THE PRODUCT'S SIDE, NOT THIS ONE. §7 of the landing
 * standard fails one mark serving two destinations. Dev.to's mark here is `code-square`, and the
 * DOCS column's "API reference" row was drawing the same file: `code` in src/components/Icon.tsx
 * was `code-square-bold-duotone` — the same picture twice in one footer, checked by reverse-mapping
 * every body in that generated file back to its Solar id rather than by reading its names. The ten
 * destinations are fixed estate-wide, so the row that moved is the product's: `api`, which is
 * `programming-bold-duotone`, and `code` is no longer vendored because nothing else used it.
 *
 * ⛔ THE BODIES ARE INLINE, AND THAT IS NOT LAZINESS. `src/components/Icon.tsx` is GENERATED by
 * kynth-ops/tools/vendor-solar-icons.mjs from an explicit per-product name list, so a component
 * that named these glyphs through it renders eight rows with no mark at all in any repo whose list
 * missed them — `Icon` returns null for a name it does not hold and nothing errors. They are
 * copied byte for byte from dev-shell/src/components/site/SocialColumn.tsx, the reference.
 *
 * Solar bold-duotone icons, CC BY 4.0 by 480 Design — https://github.com/480-Design/Solar-Icon-Set
 */
const MARKS: Record<string, string> = {
  "markx": "<path fill=\"currentColor\" d=\"M21.975 13.814A10.95 10.95 0 0 1 17 15.001C10.925 15 6 10.076 6 4q.001-.945.154-1.847c-.715.106-1.277.284-1.766.584a5 5 0 0 0-1.651 1.65C2 5.591 2 7.228 2 10.501v1c0 2.33 0 3.495.38 4.413a5 5 0 0 0 2.707 2.706c.66.274 1.447.35 2.703.372c.85.015 1.275.022 1.613.219c.337.196.548.551.968 1.262l.542.916c.483.816 1.69.816 2.174 0l.542-.916c.42-.71.63-1.066.968-1.262c.338-.197.763-.204 1.613-.219c1.256-.021 2.043-.098 2.703-.372a5 5 0 0 0 2.706-2.706c.227-.547.319-1.182.356-2.1\"/><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"m13.087 21.389l.542-.916c.42-.71.63-1.066.968-1.262c.338-.197.763-.204 1.613-.219c1.256-.021 2.043-.098 2.703-.372a5 5 0 0 0 2.706-2.706c.227-.547.319-1.182.356-2.1A10.95 10.95 0 0 1 17 15.001C10.925 15 6 10.076 6 4q.001-.945.154-1.847c-.715.106-1.277.284-1.766.584a5 5 0 0 0-1.651 1.65C2 5.591 2 7.228 2 10.501v1c0 2.33 0 3.495.38 4.413a5 5 0 0 0 2.707 2.706c.66.274 1.447.35 2.703.372c.85.015 1.275.022 1.613.219c.337.196.548.551.968 1.262l.542.916c.483.816 1.69.816 2.174 0\" clip-rule=\"evenodd\"/><path fill=\"currentColor\" d=\"M13.5 2h-3c-1.94 0-3.305 0-4.346.153Q6.001 3.055 6 4c0 6.075 4.925 11 11 11c1.79 0 3.48-.428 4.975-1.187C22 13.192 22 12.441 22 11.5v-1c0-3.273 0-4.91-.737-6.112a5 5 0 0 0-1.65-1.651C18.41 2 16.773 2 13.5 2\" opacity=\".5\"/>",
  "threads": "<path fill=\"currentColor\" d=\"M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12c0 1.76.413 3.423 1.148 4.898c.195.392.26.84.147 1.263l-.655 2.448a1.43 1.43 0 0 0 1.75 1.751l2.45-.655a1.8 1.8 0 0 1 1.262.147A10.96 10.96 0 0 0 12 23\" opacity=\".5\"/><path fill=\"currentColor\" d=\"M10.9 12a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 0 0-2.2 0m-4.4 0a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 0 0-2.2 0m8.8 0a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 0 0-2.2 0\"/>",
  "camera": "<path fill=\"currentColor\" d=\"M9.778 21h4.444c3.121 0 4.682 0 5.803-.735a4.4 4.4 0 0 0 1.226-1.204c.749-1.1.749-2.633.749-5.697s0-4.597-.749-5.697a4.4 4.4 0 0 0-1.226-1.204c-.72-.473-1.622-.642-3.003-.702c-.659 0-1.226-.49-1.355-1.125A2.064 2.064 0 0 0 13.634 3h-3.268c-.988 0-1.839.685-2.033 1.636c-.129.635-.696 1.125-1.355 1.125c-1.38.06-2.282.23-3.003.702A4.4 4.4 0 0 0 2.75 7.667C2 8.767 2 10.299 2 13.364s0 4.596.749 5.697c.324.476.74.885 1.226 1.204C5.096 21 6.657 21 9.778 21\" opacity=\".5\"/><path fill=\"currentColor\" d=\"M17.556 9.272a.826.826 0 0 0-.833.819c0 .452.373.818.833.818h1.111c.46 0 .834-.367.834-.818a.826.826 0 0 0-.834-.819z\"/><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M12 9.272c-2.3 0-4.166 1.832-4.166 4.091s1.865 4.091 4.167 4.091c2.3 0 4.166-1.831 4.166-4.09s-1.865-4.092-4.166-4.092m0 1.637c-1.38 0-2.5 1.099-2.5 2.454s1.12 2.455 2.5 2.455c1.381 0 2.5-1.099 2.5-2.455c0-1.355-1.119-2.454-2.5-2.454\" clip-rule=\"evenodd\"/>",
  "briefcase": "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M10.581 2.25h-.02c-.114 0-.202 0-.286.005a2.75 2.75 0 0 0-2.385 1.72a8 8 0 0 0-.12.343l-.004.012a1.63 1.63 0 0 1-.505.695q-.34.011-.652.03c-1.644.096-2.687.366-3.438 1.117c-.244.244-.438.52-.59.838q.086.03.166.081c2.1 1.365 3.42 2.22 4.516 2.767A.75.75 0 0 1 8.75 10v.458c2.12.64 4.38.64 6.5 0V10a.75.75 0 0 1 1.486-.142c1.097-.548 2.417-1.402 4.517-2.767a.8.8 0 0 1 .167-.081a3 3 0 0 0-.592-.838c-.75-.75-1.793-1.02-3.437-1.118q-.296-.016-.618-.028l-.04-.034a1.9 1.9 0 0 1-.525-.74l-.003-.009c-.036-.107-.064-.191-.095-.269a2.75 2.75 0 0 0-2.385-1.719a5 5 0 0 0-.286-.005zm4.237 2.566l-.005-.011l-.005-.012l-.005-.012l-.003-.01l-.002-.005l-.004-.012l-.004-.012l-.002-.006l-.003-.008l-.002-.007l-.002-.006a4 4 0 0 0-.063-.181a1.25 1.25 0 0 0-1.084-.782a4 4 0 0 0-.215-.002h-2.838c-.143 0-.183 0-.215.002a1.25 1.25 0 0 0-1.084.782l-.003.007l-.008.021a6 6 0 0 0-.078.23l-.001.006l-.003.007l-.002.008l-.002.006l-.004.012l-.005.012l-.001.005l-.004.01l-.005.012l-.004.012l-.005.01v.001l-.044.108L10 5h4.896a3 3 0 0 1-.079-.184\" clip-rule=\"evenodd\"/><path fill=\"currentColor\" d=\"M2.162 8.5C2 9.603 2 11.05 2 13c0 3.771 0 5.657 1.172 6.828S6.229 21 10 21h4c3.771 0 5.657 0 6.828-1.172S22 16.771 22 13c0-1.95 0-3.397-.162-4.5c-2.277 1.48-3.736 2.423-5.088 3.005V12a.75.75 0 0 1-1.5.016a12.75 12.75 0 0 1-6.5 0A.75.75 0 0 1 7.25 12v-.496C5.898 10.924 4.44 9.98 2.162 8.5\" opacity=\".5\"/>",
  "cloud": "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M22 14.353C22 17.472 19.442 20 16.286 20h-5.787a7.5 7.5 0 0 1 7.487-11.853q.119.422.17.868C20.392 9.78 22 11.881 22 14.353\" clip-rule=\"evenodd\" opacity=\".5\"/><path fill=\"currentColor\" d=\"M12.476 4C9.32 4 6.762 6.528 6.762 9.647c0 .69.125 1.35.354 1.962a4.4 4.4 0 0 0-.83-.08C3.919 11.53 2 13.426 2 15.765S3.919 20 6.286 20H10.5a7.5 7.5 0 0 1 7.487-11.853l-.047-.158C17.224 5.68 15.048 4 12.476 4\"/>",
  "codesquare": "<path fill=\"currentColor\" d=\"M2 12c0-4.714 0-7.071 1.464-8.536C4.93 2 7.286 2 12 2s7.071 0 8.535 1.464C22 4.93 22 7.286 22 12s0 7.071-1.465 8.535C19.072 22 16.714 22 12 22s-7.071 0-8.536-1.465C2 19.072 2 16.714 2 12\" opacity=\".5\"/><path fill=\"currentColor\" d=\"M13.488 6.446a.75.75 0 0 1 .53.918l-2.588 9.66a.75.75 0 0 1-1.449-.389l2.589-9.659a.75.75 0 0 1 .918-.53M14.97 8.47a.75.75 0 0 1 1.06 0l.209.208c.635.635 1.165 1.165 1.529 1.642c.384.504.654 1.036.654 1.68s-.27 1.176-.654 1.68c-.364.477-.894 1.007-1.53 1.642l-.208.208a.75.75 0 1 1-1.06-1.06l.171-.172c.682-.682 1.139-1.14 1.434-1.528c.283-.37.347-.586.347-.77s-.064-.4-.347-.77c-.295-.387-.752-.846-1.434-1.528l-.171-.172a.75.75 0 0 1 0-1.06m-7 0a.75.75 0 0 1 1.06 1.06l-.171.172c-.682.682-1.138 1.14-1.434 1.528c-.283.37-.346.586-.346.77s.063.4.346.77c.296.387.752.846 1.434 1.528l.172.172a.75.75 0 1 1-1.061 1.06l-.208-.208c-.636-.635-1.166-1.165-1.53-1.642c-.384-.504-.653-1.036-.653-1.68s.27-1.176.653-1.68c.364-.477.894-1.007 1.53-1.642z\"/>",
  "notes": "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"m20.83 10.715l-.518 1.932c-.605 2.255-.907 3.383-1.592 4.114a4 4 0 0 1-2.01 1.161q-.145.034-.295.052c-.915.113-2.032-.186-4.064-.73c-2.255-.605-3.383-.907-4.114-1.592a4 4 0 0 1-1.161-2.011c-.228-.976.074-2.103.679-4.358l.517-1.932l.244-.905c.455-1.666.761-2.583 1.348-3.21a4 4 0 0 1 2.01-1.16c.976-.228 2.104.074 4.36.679c2.254.604 3.382.906 4.113 1.59a4 4 0 0 1 1.161 2.012c.228.976-.075 2.103-.679 4.358m-9.778-.91a.75.75 0 0 1 .919-.53l4.83 1.295a.75.75 0 1 1-.389 1.448l-4.83-1.294a.75.75 0 0 1-.53-.918m-.776 2.898a.75.75 0 0 1 .918-.53l2.898.777a.75.75 0 1 1-.388 1.448l-2.898-.776a.75.75 0 0 1-.53-.919\" clip-rule=\"evenodd\"/><path fill=\"currentColor\" d=\"M16.415 17.975a4 4 0 0 1-1.068 1.677c-.731.685-1.859.987-4.114 1.591s-3.383.907-4.358.679a4 4 0 0 1-2.011-1.161c-.685-.731-.988-1.859-1.592-4.114l-.517-1.932c-.605-2.255-.907-3.383-.68-4.358a4 4 0 0 1 1.162-2.011c.731-.685 1.859-.987 4.114-1.592q.638-.172 1.165-.309l-.244.906l-.517 1.932c-.605 2.255-.907 3.382-.68 4.358a4 4 0 0 0 1.162 2.011c.731.685 1.859.987 4.114 1.592c2.032.544 3.149.843 4.064.73\" opacity=\".5\"/>",
  "clapper": "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M2 12c0-1.237 0-2.311.026-3.25h19.948C22 9.689 22 10.763 22 12c0 4.714 0 7.071-1.465 8.535C19.072 22 16.714 22 12 22s-7.071 0-8.536-1.465C2 19.072 2 16.714 2 12\" clip-rule=\"evenodd\" opacity=\".5\"/><path fill=\"currentColor\" d=\"M15 14.5c0-.633-.662-1.06-1.986-1.915c-1.342-.866-2.013-1.299-2.514-.98c-.5.317-.5 1.176-.5 2.895s0 2.578.5 2.896s1.172-.115 2.514-.981C14.338 15.56 15 15.133 15 14.5M12 2c1.845 0 3.33 0 4.54.088L13.098 7.25H8.401l3.5-5.25zM3.464 3.464c1.253-1.252 3.158-1.433 6.631-1.46L6.599 7.25H2.104c.147-1.764.503-2.928 1.36-3.786M21.896 7.25c-.148-1.764-.503-2.928-1.36-3.786c-.598-.597-1.344-.95-2.338-1.16L14.901 7.25z\"/>",
};

type SocialLink = { href: string; mark: string; label: string; handle: string };

/* The hrefs come from kynth-ops/social/accounts.json, the account registry — the same set the
 * generated rail carried. */
const STUDIO: SocialLink[] = [
  { href: "https://x.com/kynthstudios", mark: "markx", label: "X", handle: "@kynthstudios" },
  { href: "https://www.threads.com/@kynthstudios", mark: "threads", label: "Threads", handle: "@kynthstudios" },
  { href: "https://www.instagram.com/kynthstudios/", mark: "camera", label: "Instagram", handle: "@kynthstudios" },
  { href: "https://www.linkedin.com/company/kynth-studios", mark: "briefcase", label: "LinkedIn", handle: "Kynth Studios" },
  { href: "https://bsky.app/profile/kynth.studio", mark: "cloud", label: "Bluesky", handle: "kynth.studio" },
  { href: "https://dev.to/kynth", mark: "codesquare", label: "Dev.to", handle: "@kynth" },
  { href: "https://kynth.hashnode.dev/", mark: "notes", label: "Hashnode", handle: "kynth.hashnode.dev" },
  { href: "https://www.youtube.com/@KynthStudios", mark: "clapper", label: "YouTube", handle: "@KynthStudios" },
];

const FOUNDER: SocialLink[] = [
  { href: "https://x.com/kyisaiah47", mark: "markx", label: "X", handle: "@kyisaiah47" },
  { href: "https://www.linkedin.com/in/kyisaiah47", mark: "briefcase", label: "LinkedIn", handle: "@kyisaiah47" },
];

const LINK_COLOR = "var(--extracted-r6o4lv, var(--color-text, rgb(209, 209, 209)))";

/** One destination, in this footer's own row grammar — the same `.menu-overview-link` wrapper and
 *  the same `.small-3 … .tl-footer-row` anchor every PRODUCT, DOCS, GUIDES and CODE row uses, so
 *  the glyph size, the 8px gap and the label's type are inherited rather than re-declared. The
 *  markup is the donor's, copied verbatim; only the mark and the words differ. */
function SocialRow({ link, who }: { link: SocialLink; who: string }) {
  const title = `${who} on ${link.label} — ${link.handle}`;
  return (
    <div className={"menu-overview-link"}>
      <a
        className={"small-3 link-16 nav-link small-2 small-3-state small tl-footer-row"}
        data-name={"Small"}
        data-highlight={"true"}
        href={link.href}
        tabIndex={0}
        target={"_blank"}
        rel={"noopener me"}
        aria-label={title}
        title={title}
      >
        <svg
          className={"tl-footer-mark"}
          viewBox={"0 0 24 24"}
          width={18}
          height={18}
          role={"presentation"}
          aria-hidden={true}
          /* `--color-background` is this product's accent at full strength — theme.css says so in
             as many words — and it is what `Icon` defaults to for every other mark in this
             footer. */
          style={{ color: "var(--color-background, #ffa552)", display: "block", flex: "0 0 auto" }}
          dangerouslySetInnerHTML={{ __html: MARKS[link.mark] }}
        />
        <div className={"nav-link-label"} data-component={"RichTextContainer"}>
          <p className={"heading-4 body-text"} dir={"auto"} style={{ "--rt-text-color": LINK_COLOR }}>
            {link.label}
          </p>
        </div>
      </a>
    </div>
  );
}

/** The column, in the same `.footer-product-group` shell as PRODUCT, DOCS, GUIDES and CODE — same
 *  heading box, same label type — so it is a fifth column rather than a block bolted to the end of
 *  four.
 *
 *  ⛔ ONE GRID FOR ALL TEN ROWS, not one per group: `repeat(2, max-content)` sizes tracks to the
 *  content of THAT grid, so a founder grid of its own made its first track the width of "X"
 *  against "Instagram" above and the two blocks did not line up. The founder head spans both
 *  tracks instead. */
export default function SocialColumn() {
  return (
    <div className={"footer-product-group tl-social-col"}>
      <div className={"label-4"} data-name={"Label"}>
        <div className={"footer-product-heading"} data-component={"RichTextContainer"}>
          <p className={"heading-4 menu-label"} dir={"auto"}>{"Follow"}</p>
        </div>
      </div>
      <div className={"links-6 tl-social-grid"} data-name={"Links"}>
        {STUDIO.map((l) => (
          <SocialRow key={l.href} link={l} who={"Kynth Studios"} />
        ))}
        <p className={"heading-4 menu-label tl-social-subhead"} dir={"auto"}>{"@kyisaiah47"}</p>
        {FOUNDER.map((l) => (
          <SocialRow key={l.href} link={l} who={"@kyisaiah47"} />
        ))}
      </div>
    </div>
  );
}
